
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigInteger;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sivagnanam
 */
public class user1 extends javax.swing.JFrame {

    /**
     * Creates new form SUBSERVER1
     */
    public user1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 0, 50, 24);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(301, 60, 354, 135);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 257, 135);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bitcoin Transactions");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(73, 40, 150, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MESSAGES");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(481, 40, 74, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(301, 213, 354, 33);

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 210, 118, 28);

        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 270, 118, 31);

        jButton3.setText("meta data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 280, 120, 30);

        jButton4.setText("attack");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 280, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bitcoin", "ethereum", "litecoin", "monero" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 210, 110, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "user 1", "user 3", "user 4", "user 5" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(160, 270, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 670, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        send();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    
    
    
    
    
    
    ////////////////////server start
 
    
      Socket s;
    
    
  ServerSocket ss;
      
    public void sstart()
    {
       
         try{  
      ss =new ServerSocket(6001);
        String data;
         System.out.println("listening");
         
         while(true)
         {
              s=ss.accept();
    
	ObjectInputStream inn=new ObjectInputStream(s.getInputStream());
   Vector   b=(Vector)inn.readObject();
   
      System.out.println("the received values is"+b);
     String str1 = b.get(1).toString();
     
     
					System.out.println("the data is"+str1);
     
     
      jTextArea1.append("\namount recieved "+str1);
         
         
     if(str1.equals("close"))
     {
         this.setVisible(false);
     }
         
     ObjectOutputStream dis=new ObjectOutputStream(s.getOutputStream());
     dis.writeObject("ack");
   
         }
        }
        catch(Exception e)
        {
           System.out.println(e); 
        }
    }
   
    
    
    
    




///////////////////server end
    
    
    
    
    
    
    ///////////////////////////////////send start
    
     
     public void send()
    {
        int portt=0;
        String ss="\nuser2=>\t"+jComboBox1.getSelectedItem().toString()+"\t=>"+jTextField1.getText();
     if(jComboBox2.getSelectedItem().toString().equals("user 1"))
     {
     portt=6001;
     }
     if(jComboBox2.getSelectedItem().toString().equals("user 2"))
     {
     portt=6002;
     }
     if(jComboBox2.getSelectedItem().toString().equals("user 3"))
     {
     portt=6003;
     }
     if(jComboBox2.getSelectedItem().toString().equals("user 4"))
     {
     portt=6004;
     }
     if(jComboBox2.getSelectedItem().toString().equals("user 5"))
     {
     portt=6005;
     }
        try
        {
             s=new Socket("localhost",portt);
            System.out.println("connect");
        ObjectOutputStream out=new ObjectOutputStream(s.getOutputStream());
          Vector a = new Vector() ;
       a.add(0,"hi");
       
        
                                System.out.println("===>"+ss);
				
				    System.out.println("the value is "+ss);
           a.add(1,ss);
           out.writeObject(a);
              ObjectInputStream inn=new ObjectInputStream(s.getInputStream());
                        String b =(String) inn.readObject();
                        System.out.println(b);
    	out.flush();
	out.close();
	s.close();        
        }
        catch( Exception exe)
        {
            System.out.println(exe+"");
        }
    
    }
    
    ////////////////////////////////// send end
     
     
     
     
     
     
     
     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
     
        //</editor-fold>

        /* Create and display the form */
            user1 m=  new user1();
               m.setVisible(true);
               m.sstart();
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
